-- Multi-tenant foundation is now included in supabase/schema.sql.
-- Keep this file as a compatibility note for older execution plans.
-- Run supabase/schema.sql to create tenants, app_users, coaches, students,
-- workouts, workout_sessions, logbook_sets, RLS policies and indexes.
