-- DG TEAM APP Supabase schema
-- Canonical SQL lives in ../../supabase/schema.sql.
-- This compatibility path is kept because older docs referenced src/utils/supabaseSchema.sql.
-- Execute supabase/schema.sql in the Supabase SQL Editor for the current real-data foundation.
